name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  snake-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Ricardo399181
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Publish Snake Animation SVG
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Snake Animation URL
        run: echo "SNAKE_ANIMATION_URL=https://Ricardo399181.github.io/Ricardo399181/github-contribution-grid-snake.svg" >> $GITHUB_ENV
