name: Snake animation

on:
  schedule:
    - cron: '0 * * * *' # Executa a cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Gerar animação de cobra
      uses: Platane/snk@latest
      with:
        github_user_name: Ricardo399181 # substitua por seu nome de usuário do GitHub
        outputs:
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          dist/github-contribution-grid-snake.gif?color_snake=orange&color_bg=333333&color_dots=1A1B27
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        message: "Adiciona animação da cobra ao perfil do GitHub"
        author_name: Ricardo ferreira # substitua por seu nome
        author_email: pauloricardo399181@gmail.com # substitua por seu endereço de email
        signoff: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        branch: main # substitua pela sua branch principal
